config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from app import views
from app.views import *
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('pais/',PaisView.as_view(),name='pais'),
    path('decada/',DecadaView.as_view(),name='decada'),
    path('empresa/',EmpresaView.as_view(),name='empresa'),
    path('historiainformatica/',HistInfoView.as_view(),name='historiainformatica'),
    path('forum/',ForumView.as_view(),name='forum_list'),
    path('', forum_list, name='forum_list'),
    path('criar/', criar_forum, name='criar_forum'),
    path('<int:forum_id>/comentar/', comentar_forum, name='comentar_forum'),
    path('<int:forum_id>/responder/', responder_forum, name='responder_forum'),
    path('forum/editar/<int:id>/', editar_forum, name='editar_forum'),
    path('comentario/editar/<int:comentario_id>/', views.editar_comentario, name='editar_comentario'),
    path('resposta/editar/<int:resposta_id>/', views.editar_resposta, name='editar_resposta'),
    path('figuraimportante/',FiguraImportanteView.as_view(),name='figuraimportante'),
    path('forum/apagar/<int:id>/', views.apagar_forum, name='apagar_forum'),
    path('comentario/apagar/<int:id>/', views.apagar_comentario, name='apagar_comentario'),
    path('resposta/apagar/<int:id>/', views.apagar_resposta, name='apagar_resposta'),
    path('contas/', include('contas.urls')),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cadastro/', cadastro, name='cadastro'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.contrib import admin 
from django.urls import include, path 
from django.views.generic import TemplateView 
from app.views import *
from django.urls import path 
from django.urls import path 
from . import views
from app.views import *
from forum.views import *


urlpatterns = [
    path('forum/',ForumView.as_view(),name='forum'),
    path('forum_list/', forum_list, name='forum_list'),
    path('criar/', criar_forum, name='criar_forum'),
    path('<int:forum_id>/comentar/', comentar_forum, name='comentar_forum'),



]

projetohistinfo/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from app.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('pais/',PaisView.as_view(),name='pais'),
    path('decada/',DecadaView.as_view(),name='decada'),
    path('empresa/',EmpresaView.as_view(),name='empresa'),
    path('topico/',TopicoView.as_view(),name='topico'),
    path('usuario/',UsuarioView.as_view(),name='usuario'),
    path('historiainformatica/',HistInfoView.as_view(),name='historiainformatica'),
    path('quiz/',QuizView.as_view(),name='quiz'),
    path('forum/',ForumView.as_view(),name='forum'),
    path('ranking/',RankingView.as_view(),name='ranking'),
    path('figuraimportante/',FiguraImportanteView.as_view(),name='figuraimportante'),
    path('configuracao/',ConfiguracaoView.as_view(),name='configuracao'),
    path('postagemforum/',PostagemForumView.as_view(),name='postagemforum'),
    path('comentarioforum/',ComentarioForumView.as_view(),name='comentarioforum'),
    path('comentarioquiz/',ComentarioQuizView.as_view(),name='comentarioquiz'),
    path('pesquisa/',PesquisaView.as_view(),name='pesquisa'),
   
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User


class Forum(models.Model):
    nome = models.CharField(max_length=255)
    topico = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='foruns',null=True)  # Adicione related_name
    datainicio = models.DateTimeField(auto_now_add=True)
    datatermino = models.DateTimeField(null=True, blank=True)

    def _str_(self):
        return self.nome

class Comentario(models.Model):
    forum = models.ForeignKey(Forum, related_name='comentarios', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comentarios', null=True)  # Adicione related_name
    texto = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"{self.user.first_name}: {self.texto}"

forum/views.py
# from app.models import Forum, Comentario
# from django.shortcuts import render, redirect, get_object_or_404
# from .models import *
# from django.views import View
# from django.contrib.auth.decorators import login_required
# from app.forms import ComentarioForm

# @login_required
# def forum_list(request):
#     foruns = Forum.objects.all()
#     return render(request, 'forum/forum_list.html', {'foruns': foruns})

# @login_required
# def criar_forum(request):
#     if request.method == 'POST':
#         nome = request.POST['nome']
#         topico = request.POST['topico']
#         forum = Forum(nome=nome, topico=topico, usuario=request.user)
#         forum.save()
#         return redirect('forum_list')
#     return render(request, 'forum/criar_forum.html')

# @login_required
# def comentar_forum(request, forum_id):
#     forum = get_object_or_404(Forum, id=forum_id)
#     if request.method == 'POST':
#         form = ComentarioForm(request.POST)
#         if form.is_valid():
#             comentario = form.save(commit=False)
#             comentario.forum = forum
#             comentario.usuario = request.user
#             comentario.save()
#             return redirect('forum_list')
#     else:
#         form = ComentarioForm()
#     return render(request, 'forum/comentar_forum.html', {'form': form, 'forum': forum})
# @login_required
# def criar_forum(request):
#     if request.user.is_staff:
#         if request.method == 'POST':
#             nome = request.POST.get('nome')
#             topico = request.POST.get('topico')
#             forum = Forum(nome=nome, topico=topico, usuario=request.user)
#             forum.save()
#             return redirect('forum_list')
#         return render(request, 'forum/criar_forum.html')
#     else:
#         return redirect('forum_list')
from django.shortcuts import get_object_or_404, redirect # type: ignore
from .models import Forum, Comentario

def apagar_forum(request, id):
    if request.method == 'POST':
        forum = get_object_or_404(Forum, id=id)
        forum.delete()
        return redirect('home')  # Redirecione para a página inicial ou outra página que você desejar

def apagar_comentario(request, id):
    if request.method == 'POST':
        comentario = get_object_or_404(Comentario, id=id)
        comentario.delete()
        return redirect('home')  # Redirecione para a página inicial ou outra página que você desejar

forum/templates/comentar_forum.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comentar Fórum</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: rgb(172, 167, 167);
        }

        header {
            background-color: black;
            color: white;
            text-align: center;
            padding: 20px;
            border: solid white 2px;
        }

        nav {
            background-color: black;
            padding: 10px 0;
            border: solid white 2px;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: center;
        }

        nav li {
            margin: 0 20px;
        }

        nav a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            display: block;
        }

        nav a:hover {
            background-color: #333;
            border-radius: 4px;
        }

        .box {
            max-width: 800px;
            margin: 30px auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .box2 {
            padding: 20px;
            background-color: rgb(195, 188, 188);
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            text-align: left;
        }

        .label {
            margin-bottom: 10px;
            display: block;
            font-weight: bold;
            font-size: 16px;
        }

        textarea {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 15px;
            font-size: 16px;
            height: 120px;
        }

        .botao, .botao2, .botao3 {
            width: 100%;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            text-decoration: none;
            color: whitesmoke;
            margin: 10px 0;
            border: none;
            font-size: 16px;
        }

        .botao {
            background-color: rgb(10, 175, 10);
        }

        .botao2 {
            background-color: rgb(221, 19, 4);
        }

        .botao3 {
            background-color: rgb(92, 89, 89);
        }

        .botao:hover, .botao2:hover, .botao3:hover {
            opacity: 0.9;
        }

        .titulo {
            text-align: center;
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(179, 179, 179, 0.829);
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            font-size: 24px;
            font-weight: bold;
        }

        div {
            text-align: center;
        }
        .login-button {
            position: absolute;
            right: 20px;
            top: 20px;
            background-color: rgb(10, 175, 10);
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .login-button:hover {
            background-color: rgb(0, 150, 0);
        }
    </style>
</head>
<body>
    <header>
        <h1>SITE SOBRE A HISTÓRIA DA INFORMÁTICA</h1>
        <a href="{% url 'login' %}" class="login-button">Login</a>
    </header>
    <nav>
        <ul>
            <li><a href="/">PÁGINA PRINCIPAL</a></li>
            <li><a href="/historiainformatica/">HISTÓRIA DA INFORMÁTICA</a></li>
            <li><a href="/forum/">FÓRUNS</a></li>
        </ul>
    </nav>
    
    <h2 class="titulo">Comentar no Fórum: {{ forum.nome }}</h2>
    
    <div class="box">
        <form method="POST">
            <div class="box2">
                {% csrf_token %}
                
                <label class="label" for="id_texto">Texto do Comentário</label>
                <textarea name="texto" id="id_texto" required aria-setsize="40"></textarea>
            </div>
            
            <button type="submit" class="botao">Comentar</button>
            <button type="reset" class="botao2">Limpar</button>
        </form>

        <br>
        <a href="{% url 'forum_list' %}" class="botao3">Voltar para a Lista de FÓRUNS</a>
    </div>
</body>
</html>

forum/templates/editar_comentario.html

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Comentário</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: rgb(172, 167, 167);
        }

        header {
            background-color: black;
            color: white;
            text-align: center;
            padding: 20px;
            border: solid white 2px;
        }

        nav {
            background-color: black;
            padding: 10px 0;
            border: solid white 2px;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: center;
        }

        nav li {
            margin: 0 20px;
        }

        nav a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            display: block;
        }

        nav a:hover {
            background-color: #333;
            border-radius: 4px;
        }

        .box {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .input-container {
            max-width: 700px;
            margin: 10px auto;
            text-align: left;
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        textarea,
        input[type="file"] {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 15px;
            font-size: 16px;
        }

        textarea {
            height: 150px;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 8px;
            cursor: pointer;
        }

        .botao {
            background-color: rgb(10, 175, 10);
            color: white;
            border: none;
            margin: 10px 0;
            text-align: center;
            width: 100%;
        }

        .botao:hover {
            background-color: rgb(0, 150, 0);
        }

        .botao2 {
            background-color: rgb(221, 19, 4);
            width: 100%;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            text-decoration: none;
            color: whitesmoke;
            margin: 10px 0;
            border: none;
            font-size: 16px;
        }

        .botao2:hover {
            background-color: rgb(180, 0, 0);
        }

        .titulo {
            text-align: center;
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(179, 179, 179, 0.829);
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            font-size: 24px;
            font-weight: bold;
        }

        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            background-color: #ccc;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            color: white;
        }

        .form-footer a:hover {
            background-color: #999;
        }
        .login-button {
            position: absolute;
            right: 20px;
            top: 20px;
            background-color: rgb(10, 175, 10);
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .login-button:hover {
            background-color: rgb(0, 150, 0);
        }
    </style>
</head>
<body>
    <header>
        <h1>SITE SOBRE A HISTÓRIA DA INFORMÁTICA</h1>
        <a href="{% url 'login' %}" class="login-button">Login</a>
    </header>
    <nav>
        <ul>
            <li><a href="/">PÁGINA PRINCIPAL</a></li>
            <li><a href="/historiainformatica/">HISTÓRIA DA INFORMÁTICA</a></li>
            <li><a href="/forum/">FÓRUNS</a></li>
        </ul>
    </nav>

    <div class="box">
        <form method="POST">
            {% csrf_token %}
            
            <div class="input-container">
                <label for="id_texto">Texto do Comentário</label>
                {{ form.as_p }} 
            </div>
            
            <button type="submit" class="botao">Salvar Alterações</button>
            <div class="form-footer">
                <a href="{% url 'forum_list' %}" class="botao2">Cancelar</a>
            </div>
        </form>
    </div>
</body>
</html>

forum/templates/editar_forum.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Fórum</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: rgb(172, 167, 167);
        }

        header {
            background-color: black;
            color: white;
            text-align: center;
            padding: 20px;
            border: solid white 2px;
        }

        nav {
            background-color: black;
            padding: 10px 0;
            border: solid white 2px;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: center;
        }

        nav li {
            margin: 0 20px;
        }

        nav a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            display: block;
        }

        nav a:hover {
            background-color: #333;
            border-radius: 4px;
        }

        .box {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .box2 {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: rgb(133, 133, 133);
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .input-container {
            max-width: 700px;
            margin: 10px auto;
            text-align: left;
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        textarea,
        input[type="file"] {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 15px;
            font-size: 16px;
        }

        textarea {
            height: 150px;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 8px;
            cursor: pointer;
        }

        .botao {
            background-color: rgb(10, 175, 10);
            color: white;
            border: none;
            margin: 10px 0;
            text-align: center;
            width: 100%;
        }

        .botao:hover {
            background-color: rgb(0, 150, 0);
        }

        .botao2 {
            background-color: rgb(221, 19, 4);
            width: 100%;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            text-decoration: none;
            color: whitesmoke;
            margin: 10px 0;
            border: none;
            font-size: 16px;
        }

        .botao2:hover {
            background-color: rgb(180, 0, 0);
        }

        .titulo {
            text-align: center;
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(179, 179, 179, 0.829);
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            font-size: 24px;
            font-weight: bold;
        }

        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            background-color: #ccc;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            color: white;
        }

        .form-footer a:hover {
            background-color: #999;
        }
        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            background-color: #ccc;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            color: white;
        }

        .form-footer a:hover {
            background-color: #999;
        }
        .login-button {
            position: absolute;
            right: 20px;
            top: 20px;
            background-color: rgb(10, 175, 10);
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .login-button:hover {
            background-color: rgb(0, 150, 0);
        }
    </style>
</head>
<body>
    <header>
        <h1>SITE SOBRE A HISTÓRIA DA INFORMÁTICA</h1>
        <a href="login/" class="login-button">Login</a>
    </header>
    <nav>
        <ul>
            <li><a href="/">PÁGINA PRINCIPAL</a></li>
            <li><a href="/historiainformatica/">HISTÓRIA DA INFORMÁTICA</a></li>
            <li><a href="/forum/">FÓRUNS</a></li>
        </ul>
    </nav>
    <h1 class="box2">Editar Fórum: {{ forum.nome }}</h1>
    <div class="box">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="input-container">
                <label for="id_nome">Nome do Fórum:</label>
                <input type="text" id="id_nome" name="nome" value="{{ forum.nome }}" required>
            </div>


            <div class="input-container">
                <label for="id_topico">Tópico:</label>
                <input type="text" id="id_topico" name="topico" value="{{ forum.topico }}" required>
            </div>

            <div class="input-container">
                <label for="id_datatermino">Data de Término:</label>
                <input type="datetime-local" id="id_datatermino" name="datatermino" value="{{ forum.datatermino }}" required>
            </div>

            <div class="input-container">
                <label for="id_proposta">Proposta:</label>
                <textarea id="id_proposta" name="proposta" required>{{ forum.proposta }}</textarea>
            </div>

 
            <div class="input-container">
                <label for="id_imagem">Imagem (opcional):</label>
                <input type="file" id="id_imagem" name="imagem">
            </div>

            <button type="submit" class="botao">Salvar Alterações</button>
        </form>

        <br>
        <a href="{% url 'forum_list' %}" class="botao2">Voltar para a Lista de Fóruns</a>
    </div>
</body>
</html>

forum/templates/editar_resposta.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Comentário</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: rgb(172, 167, 167);
        }

        header {
            background-color: black;
            color: white;
            text-align: center;
            padding: 20px;
            border: solid white 2px;
        }

        nav {
            background-color: black;
            padding: 10px 0;
            border: solid white 2px;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: center;
        }

        nav li {
            margin: 0 20px;
        }

        nav a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            display: block;
        }

        nav a:hover {
            background-color: #333;
            border-radius: 4px;
        }

        .box {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .input-container {
            max-width: 700px;
            margin: 10px auto;
            text-align: left;
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        textarea,
        input[type="file"] {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 15px;
            font-size: 16px;
        }

        textarea {
            height: 150px;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 8px;
            cursor: pointer;
        }

        .botao {
            background-color: rgb(10, 175, 10);
            color: white;
            border: none;
            margin: 10px 0;
            text-align: center;
            width: 100%;
        }

        .botao:hover {
            background-color: rgb(0, 150, 0);
        }

        .botao2 {
            background-color: rgb(221, 19, 4);
            width: 100%;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            text-decoration: none;
            color: whitesmoke;
            margin: 10px 0;
            border: none;
            font-size: 16px;
        }

        .botao2:hover {
            background-color: rgb(180, 0, 0);
        }

        .titulo {
            text-align: center;
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: rgba(179, 179, 179, 0.829);
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            font-size: 24px;
            font-weight: bold;
        }

        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            background-color: #ccc;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            color: white;
        }

        .form-footer a:hover {
            background-color: #999;
        }
        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            background-color: #ccc;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            color: white;
        }

        .form-footer a:hover {
            background-color: #999;
        }
        .login-button {
            position: absolute;
            right: 20px;
            top: 20px;
            background-color: rgb(10, 175, 10);
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .login-button:hover {
            background-color: rgb(0, 150, 0);
        }
    </style>
</head>

<body>
    <header>
        <h1>SITE SOBRE A HISTÓRIA DA INFORMÁTICA</h1>
        <a href="{% url 'login' %}" class="login-button">Login</a>
    </header>
    <nav>
        <ul>
            <li><a href="/">PÁGINA PRINCIPAL</a></li>
            <li><a href="/historiainformatica/">HISTÓRIA DA INFORMÁTICA</a></li>
            <li><a href="/forum/">FÓRUNS</a></li>
        </ul>
    </nav>

    <div class="box">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="input-container">
                <label for="id_texto">Texto da Resposta</label>
                
                {{ form.as_p }}
                {% if resposta.imagem %}
                <div class="imagem-atual">
                    <p>Imagem Atual:</p>
                    <img src="{{ resposta.imagem.url }}" alt="Imagem do Comentário" style="width: 200px;">
                </div>
                {% endif %}
            </div>

            <button type="submit" class="botao">Salvar Alterações</button>
            <div class="form-footer">
                <a href="{% url 'forum_list' %}" class="botao2">Cancelar</a>
            </div>
        </form>
    </div>
</body>

</html>